---
    - name: create /etc/letsencrypt hierarchy
      file: "dest=/etc/{{ item }}
             owner=root group=ssl-cert
             state=directory mode=0750"
      with_items:
        - "letsencrypt"
        - "letsencrypt/live"
        - "letsencrypt/live/{{ domain }}"

    - name: copy over pregenerated certificate data
      copy: "dest=/etc/letsencrypt/live/{{ domain }}/{{ item }}
             src=keys/{{ letsencrypt_fake }}/{{ item }}
             mode=0640 owner=root group=ssl-cert"
      with_items:
        - fullchain.pem
        - chain.pem
        - cert.pem
        - privkey.pem
