---
  # see packages.yml for gstreamer package installation

  - name: create voctomix directories
    file: dest={{ item }} state=directory
          owner=root group=root
    with_items:
      - /opt/voctomix/release/
      - /opt/voctomix/ansible-generated-scripts/

  - name: checkout voctomix release
    git: repo=https://c3voc.de/git/voctomix
         dest=/opt/voctomix/release/
         version=0.2
         force=yes
         accept_hostkey=yes

  - name: create voctocore systemd-unit
    template: src=systemd-units/voctocore.service.j2
              dest=/etc/systemd/system/voctocore.service
              mode=0755 owner=root group=root

  - name: create voctocore config
    template: src=voctomix-config/voctocore-config.ini.j2
              dest=/opt/voctomix/voctocore-config.ini
              mode=0755 owner=root group=root


  - name: enable voctocore service
    service: name=voctocore
             enabled=yes
             state=started
    when: encodermode is defined and encodermode == 'hd-voctomix'

  - name: disabled voctocore service
    service: name=voctocore
             enabled=no
             state=stopped
    when: encodermode is not defined or encodermode != 'hd-voctomix'
