---
  # see packages.yml for grabbersource package installation

  # grabbersource configuration
  - name: create service directory for grabbersource
    file: dest=/etc/service/grabbersource state=directory
          owner=root group=root

  - name: create runit grabbersource file
    template: dest=/etc/service/grabbersource/run
              src=grabbersource/run.j2
              owner=root group=root mode=0755

  - name: create runit grabbersource-down-file file when not in dvsplit-mode
    file: dest=/etc/service/grabbersource/down
          state=touch
          owner=root group=root mode=0655
    when: encodermode is defined and encodermode != 'sd-dvswitch'

  - name: remove runit grabbersource-down-file file when in dvsplit-mode
    file: dest=/etc/service/grabbersource/down
          state=absent
    when: encodermode is not defined or encodermode == 'sd-dvswitch'
