---
  # see packages.yml for grabbersource package installation

  # grabbersource configuration
  - name: create service directory for dvsink
    file: dest=/etc/service/grabbersource state=directory
          owner=root group=root

  - name: create runit grabbersource file
    template: dest=/etc/service/grabbersource/run
              src=grabbersource/run.j2
              owner=root group=root mode=0755
