---
  # see packages.yml for sdi-script package installation

  # sdi-script configuration
  - name: create sdi-script directories
    file: dest={{ item }} state=directory
          owner=root group=root
    with_items:
      - /etc/sdi-script
      - /etc/sdi-script/saalN-sd-dvswitch
      - /etc/sdi-script/saalN-sd-dvswitch-nostream

  # sd chain
  - name: create /etc/sdi-script/saalN-sd-dvswitch/config
    template: dest=/etc/sdi-script/saalN-sd-dvswitch/config
              src=sdi-script/saalN-sd-dvswitch/config.j2
              owner=root group=root mode=0644

  - name: create runit dvsink file
    template: dest=/etc/sdi-script/saalN-sd-dvswitch/supertee.ini
              src=sdi-script/saalN-sd-dvswitch/supertee.ini.j2
              owner=root group=root mode=0755

  # no stream
  - name: create /etc/sdi-script/saalN-sd-dvswitch-nostream/config
    template: dest=/etc/sdi-script/saalN-sd-dvswitch-nostream/config
              src=sdi-script/saalN-sd-dvswitch-nostream/config.j2
              owner=root group=root mode=0644

  - name: create runit dvsink file
    template: dest=/etc/sdi-script/saalN-sd-dvswitch-nostream/supertee.ini
              src=sdi-script/saalN-sd-dvswitch-nostream/supertee.ini.j2
              owner=root group=root mode=0755
