---
  # see packages.yml for sdi-script package installation

  # sdi-script configuration
  - name: create sdi-script directories
    file: dest={{ item }} state=directory
          owner=root group=root
    with_items:
      - /etc/sdi-script
      - /etc/sdi-script/saalN-sd-dvswitch
      - /etc/sdi-script/saalN-sd-dvswitch-nostream
      - /etc/sdi-script/saalN-hd-direct
      - /etc/sdi-script/saalN-hd-direct-recording
      - /etc/sdi-script/saalN-hd-slides-recording

  # sd chain
  - name: create /etc/sdi-script/saalN-sd-dvswitch/config
    template: dest=/etc/sdi-script/saalN-sd-dvswitch/config
              src=sdi-script/saalN-sd-dvswitch/config.j2
              owner=root group=root mode=0644

  - name: create /etc/sdi-script/saalN-sd-dvswitch/supertee.ini
    template: dest=/etc/sdi-script/saalN-sd-dvswitch/supertee.ini
              src=sdi-script/saalN-sd-dvswitch/supertee.ini.j2
              owner=root group=root mode=0755

  # sd no stream
  - name: create /etc/sdi-script/saalN-sd-dvswitch-nostream/config
    template: dest=/etc/sdi-script/saalN-sd-dvswitch-nostream/config
              src=sdi-script/saalN-sd-dvswitch-nostream/config.j2
              owner=root group=root mode=0644

  - name: create /etc/sdi-script/saalN-sd-dvswitch-nostream/supertee.ini
    template: dest=/etc/sdi-script/saalN-sd-dvswitch-nostream/supertee.ini
              src=sdi-script/saalN-sd-dvswitch-nostream/supertee.ini.j2
              owner=root group=root mode=0755



  # hd-direct chain
  - name: create /etc/sdi-script/saalN-hd-direct/config
    template: dest=/etc/sdi-script/saalN-hd-direct/config
              src=sdi-script/saalN-hd-direct/config.j2
              owner=root group=root mode=0644

  - name: create /etc/sdi-script/saalN-hd-direct/supertee.ini
    template: dest=/etc/sdi-script/saalN-hd-direct/supertee.ini
              src=sdi-script/saalN-hd-direct/supertee.ini.j2
              owner=root group=root mode=0755

  # hd-direct recording
  - name: create /etc/sdi-script/saalN-hd-direct-recording/config
    template: dest=/etc/sdi-script/saalN-hd-direct-recording/config
              src=sdi-script/saalN-hd-direct-recording/config.j2
              owner=root group=root mode=0644



  # hd-slides recrding
  - name: create /etc/sdi-script/saalN-hd-slides-recording/config
    template: dest=/etc/sdi-script/saalN-hd-slides-recording/config
              src=sdi-script/saalN-hd-slides-recording/config.j2
              owner=root group=root mode=0644
