---
  - name: install slim package
    apt: name=slim state=present

  - name: configure /etc/slim.conf
    copy: dest=/etc/slim.conf force=yes
          src=slim/slim.conf
          owner=root group=root mode=0644
