---
  # Unit cleanup
  - name: find old units
    shell: (grep -l "#MANAGED BY ANSIBLE" -r /etc/systemd/system/) | xargs -rl1 basename
    register: old_units

  - debug: msg="{{ old_units.stdout_lines }}"

  - name: disable & stop old units
    service: name={{ item }}
            enabled=no
            state=stopped
    with_items: "{{ old_units.stdout_lines }}"
    ignore_errors: yes

  - name: remove old unit-files
    file: state=absent path="/etc/systemd/system/{{ item }}"
    with_items: old_units.stdout_lines

  # Scripts
  - name: copy transcoding scripts
    copy: dest=/opt/voc/transcoding/
          src=transcoding/
          mode=0755 owner=root group=root

  - name: template h264 transcoding script
    template: dest=/opt/voc/transcoding/transcode_h264.sh
              src=transcoding/transcode_h264.sh.j2
              mode=0755 owner=root group=root

  - name: template vp8 transcoding script
    template: dest=/opt/voc/transcoding/transcode_vp8.sh
              src=transcoding/transcode_vp8.sh.j2
              mode=0755 owner=root group=root

  # Mkv-Pull
  - name: create systemd units for mkv pull
    template: src=systemd-units/pull-mkv.service.j2
              dest="/etc/systemd/system/pull-mkv-{{ item.stream }}.service"
              mode=0644 owner=root group=root
    with_items: "{{ transcode_streams }}"

  - name: enable mkv-pull units
    service: name=pull-mkv-{{ item.stream }}.service
             enabled=yes
    with_items: "{{ transcode_streams }}"

  # Transcodings
  - name: create systemd units for transcoding
    template: src="systemd-units/transcode.service.j2"
              dest="/etc/systemd/system/transcode-{{ item[0] }}-{{ item[1].stream }}.service"
              mode=0644 owner=root group=root
    with_nested:
      - [vp8, h264]
      - "{{ transcode_streams }}"

  - name: enable transcoding units
    service: name="transcode-{{ item[0] }}-{{ item[1].stream }}.service"
             enabled=yes
    with_nested:
      - [vp8, h264]
      - "{{ transcode_streams }}"

  # Mkv-Push
  - name: create systemd units for mkv push
    template: src="systemd-units/push-mkv.service.j2"
              dest="/etc/systemd/system/push-mkv-{{ item[0] }}-{{ item[1].stream }}-{{ item[2].host }}.service"
    with_nested:
      - [vp8, h264]
      - "{{ transcode_streams }}"
      - "{{ push_transcoding }}"

  - name: enable mkv-push units
    service: name="push-mkv-{{ item[0] }}-{{ item[1].stream }}-{{ item[2].host }}.service"
             enabled=yes
    with_nested:
      - [vp8, h264]
      - "{{ transcode_streams }}"
      - "{{ push_transcoding }}"

  # Reload systemd daemon
  - name: reload systemd daemon
    command: systemctl daemon-reload
    changed_when: false

  # Restart icedist
  - name: restart icedist
    service: name=icedist.service
             state=restarted
    changed_when: false
