---
  - set_fact:
      transcoding_capabilities: extended

  - name: create directories
    file: dest={{ item }} state=directory
          owner=root group=root
    with_items:
      - /opt/transcoder/scripts/


  - name: create vp9 transcode-script
    template: dest=/opt/transcoder/scripts/s{{ item }}_vp9.sh
              src=transcoder/vp9.sh.j2
              owner=root group=root mode=0755
    with_items: "{{ transcoder_vp9_streams }}"



  - name: create transcode systemd-units
    template: src=systemd-units/transcode.service.j2
              dest="/etc/systemd/system/transcode_s{{ item.0 }}_{{ item.1 }}.service"
              mode=0644 owner=root group=root
    with_nested:
      - "{{ transcoder_vp9_streams }}"
      - ["vp9"]

  - name: create transcode systemd-target
    template: src=systemd-units/transcode.target.j2
              dest="/etc/systemd/system/transcode_s{{ item }}.target"
              mode=0644 owner=root group=root
    with_items:
      - "{{ transcoder_vp9_streams }}"



  - name: reload systemd daemon
    command: systemctl daemon-reload
    changed_when: false

  - name: enable transcode systemd-units
    service: name=transcode_s{{ item.0 }}_{{ item.1 }}.service
             enabled=yes
             state=restarted
    with_nested:
      - "{{ transcoder_vp9_streams }}"
      - ["vp9"]

  - name: enable & start transcode systemd-target
    service: name=transcode_s{{ item }}.target
             enabled=yes
    with_items:
      - "{{ transcoder_vp9_streams }}"

