---
  - name: create directories
    file: dest={{ item }} state=directory
          owner=root group=root
    with_items:
      - /opt/transcoding/scripts/
      - /srv/hls

  - include: _stream.yml
    with_nested:
      - transcoding.rooms                        # room      - item.0
      - ['hd', 'sd', 'slides', 'audio']          # quality   - item.1
      - ['native', 'translated', 'translated-2'] # language  - item.2
      - ['webm', 'hls', 'opus', 'mp3']           # transport - item.3
