---
  - name: create directories
    file: dest={{ item }} state=directory
          owner=root group=root
    with_items:
      - /opt/transcoder/scripts/
      - /srv/hls


  - name: create hls-script for s{{ item }}
    template: dest=/opt/transcoder/scripts/s{{ item }}_hls.sh
              src=transcoder/hls.sh.j2
              owner=root group=root mode=755
    with_items: "{{ transcoder_rooms }}"
    tags: tscripts

  # - name: create webm transcode-script for s{{ item.0 }}
  #   template: dest=/opt/transcoder/scripts/s{{ item.0 }}_webm.sh
  #             src=transcoder/transcode-webm.sh.j2
  #             owner=root group=root mode=755
  #   with_items: "{{ transcoder_rooms }}"

  # - name: create audio transcode-script for s{{ item.0 }}
  #   template: dest=/opt/transcoder/scripts/s{{ item.0 }}_audio.sh
  #             src=transcoder/transcode-audio.sh.j2
  #             owner=root group=root mode=755
  #   with_items: "{{ transcoder_rooms }}"
