---
  - name: copy yate init script
    copy: dest=/etc/init.d/yate
          src=yate/init.d/yate
          owner=root group=root mode=0755

  - name: configure yate
    template: dest=/etc/yate/regfile.conf
              src=yate/regfile.conf.j2
              owner=root group=root mode=0644
    notify: reload yate

  - name: enable yate start
    lineinfile: dest=/etc/default/yate
                regexp="^[#N]+O_START="
                line="NO_START=0"

  - name: start yate
    service: name=yate enabled=yes state=started
