---
  # Deploy initial check_mk object config
  # TODO: not all service checks are adopted
  #       we have to run check_mk -II after first deployment
  - name: create initial check_mk objects file
    stat: path=/etc/icinga/objects/check_mk/check_mk_objects.cfg
    register: check_mk_objects
  - copy: dest=/etc/icinga/objects/check_mk/check_mk_objects.cfg
          src=../../files/monitoring-server/icinga/check_mk_objects.cfg
    when: not check_mk_objects.stat.exists

  # Configure check_mk
  # TODO: should be created more dynamically
  - name: configure check_mk
    copy: dest=/etc/check_mk/main.mk
          src=../../files/monitoring-server/main.mk
          owner=root group=root mode=0644
    notify: reload check_mk

  - name: add SSH private key for nagios user
    copy: dest=/var/lib/icinga/id_rsa
          src=../../files/monitoring-server/icinga_id_rsa
          owner=nagios group=nagios mode=0600
    # usage: ssh -v -4 -l check-mk -i /var/lib/icinga/id_rsa subtitles.ber.c3voc.de
