---
  # TODO: munin.conf should generated dynamically
  - name: adding munin.conf configuration
    copy: dest=/etc/munin/munin.conf
          src=../../files/monitoring-server/munin/munin.conf
          mode=0644 owner=root group=root

  - name: create munin user .ssh directory
    file: path=/var/lib/munin/.ssh state=directory
          owner=munin group=munin mode=0700

  - name: add SSH private key for munin user
    copy: dest=/var/lib/munin/.ssh/id_ecdsa
          src=../../files/monitoring-server/munin_id_ecdsa
          owner=munin group=munin mode=0600

  # TODO: file should be created dynamically
  # Deploy initial known_hosts file for munin user
  - name: create initial known_hosts file for munin user
    stat: path=/var/lib/munin/.ssh/known_hosts
    register: known_hosts
  - copy: dest=/var/lib/munin/.ssh/known_hosts
          src=../../files/monitoring-server/known_hosts
          mode=0640 owner=munin group=munin
    when: not known_hosts.stat.exists

  # Configure apache for munin
  - name: create munin apache config file
    copy: dest=/etc/munin/apache.conf
          src=../../files/monitoring-server/munin/apache.conf
          owner=root group=root mode=0644
    notify: reload apache

  - name: include munin apache.conf into apache
    file: state=link
          src=/etc/munin/apache.conf
          dest=/etc/apache2/conf.d/munin.conf
    notify: reload apache
