---
  - include: ../../../register/bin_path.yml
  - include: ../../letsencrypt/tasks/main.yml domain={{ ansible_fqdn }}
  - include: nginx.yml
    tags: nginx
  - include: php.yml
    tags: php
  - include: streaming_website.yml
  - include: haproxy.yml
    tags: haproxy
  - include: ocsp.yml
  - include: sysctl.yml
    tags: sysctl
  - include: iptables.yml
    tags: iptables
