---
  - name: Check if kernel "{{ system.kernel_package }}" is installed
    command: dpkg-query -W "{{ system.kernel_package }}"
    register: linux_kernel_installed
    ignore_errors: True
    when: system.kernel_package is defined

  - name: install linux specific kernel
    apt: deb="{{ item }}"
    when:
      - linux_kernel_installed|failed and kernel_urls is defined
    with_items: "{{ system.kernel_urls }}"

  - name: install linux specific kernel {{ system.kernel_package }}
    apt: name={{ item }} state=present
    with_items:
      - "{{ system.kernel_package }}"
      - "{{ system.kernel_package | regex_replace('image', 'headers') }}"
    when:
      - linux_kernel_installed|failed and kernel_urls is undefined
