---
  - include: ../../../register/bin_path.yml
  - include: resolv.yml
  - include: apt_proxy.yml
  - include: repos.yml
  - include: packages.yml
  - include: kernel.yml
  - include: vim.yml
  - include: sudo.yml
  - include: grub.yml
  - include: ntp.yml
    when: ansible_virtualization_type != 'lxc'
  - include: acpi.yml
  - include: inittab.yml
  - include: molly-guard.yml
  - include: ssh_known_hosts.yml
  - include: ssl.yml
  # realise users
  - include: user.yml user={{ users }}
    tags: user




  - name: setting voc password
    user: name=voc
          password={{ user_voc_password | default('$6$xQDo3Tyf$q8mxcBQTKmaGUA2cHuCS0QoeHSyYwESkyq/53OmEYLErMWF.CpS9Q3NzAoeB3zntZBpysfmEQ9r6sLjubLq5F1') }}
    tags: user

  - name: clear voc user authorized_keys
    authorized_key: user=voc manage_dir=true key=""
    tags: user

  - name: add all SSH keys to voc user
    authorized_key: user=voc manage_dir=true key="{{ lookup('file', item) }}"
    with_fileglob:
      - user/*/authorized_keys
    tags: user

  # Modify message of the day
  - name: adding message of the day
    template: dest=/etc/motd
              src=motd/motd
              owner=root group=root mode=0644
