---
 # general
 - name: setup the VOC debian repo key
   apt_key: data="{{ lookup('file', 'voc_repo.key') }}" state=present
   tags:
     - repo
     - gpg

 - name: ensure that the debian keyrings are present
   apt: name={{ item }} state=present update_cache=yes
   with_items:
    - debian-keyring
    - debian-archive-keyring

 - name: ensure that the debian multimedia keyring is present
   apt:
     name={{ item }}
     state=present
     update_cache=yes
     cache_valid_time=7200
     allow_unauthenticated=true
   with_items:
    - deb-multimedia-keyring
   when: ansible_distribution_release == 'jessie' and system.type == 'pi'
   tags: packages

 # jessie specific
 - name: remove /etc/apt/sources.list
   file: dest=/etc/apt/sources.list state=absent

 - name: remove /etc/apt/sources.list.d/*
   file: dest=/etc/apt/sources.list.d/{{ item }} state=absent
   with_items:
    - ftp_debian_org_debian.list
    - raspi.list

 - name: setup the VOC debian repo for jessie
   apt_repository: repo="deb http://mng.ber.c3voc.de/debian/ jessie main" state=present
   when: ansible_distribution_release == 'jessie' and system.type == 'pc'

 - name: setup the debian backports repo for jessie
   apt_repository: repo="deb http://ftp.de.debian.org/debian jessie-backports main"
   when: ansible_distribution_release == 'jessie' and system.type == 'pc'

 - name: ensure that the non-free suite is enabled for jessie
   apt_repository: repo="deb http://ftp.de.debian.org/debian jessie main contrib non-free"
   when: ansible_distribution_release == 'jessie' and system.type == 'pc'

 - name: ensure that security updates enabled for jessie
   apt_repository: repo="deb http://security.debian.org/ jessie/updates main contrib non-free"
   when: ansible_distribution_release == 'jessie' and system.type == 'pc'

 - name: setup the raspbian debian repo for jessie
   apt_repository: repo="deb http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi" state=present
   when: ansible_distribution_release == 'jessie' and system.type == 'pi'

 - name: setup the raspbian debian repo for jessie
   apt_repository: repo="deb http://archive.raspberrypi.org/debian/ jessie main ui" state=present
   when: ansible_distribution_release == 'jessie' and system.type == 'pi'

 - name: setup the armhf debian multimedia repo for jessie
   apt_repository: repo="deb http://deb-multimedia.org stable main non-free" state=present
   when: ansible_distribution_release == 'jessie' and system.type == 'pi'

 - name: pin multimedia packages for arm ffmpeg*
   template: src="apt-pin-ffmpeg-multimedia.pref.j2"
             dest="/etc/apt/preferences.d/apt-pin-ffmpeg-multimedia.pref"
             mode=0644 owner=root group=root
   when: ansible_distribution_release == 'jessie' and system.type == 'pi'
