---
  - name: install icecast streaming server
    apt: name=icecast2-beta state=latest

  - name: configure the icecast streaming server
    template: dest=/etc/icecast2-beta/icecast.xml
              src=icecast/icecast.xml.j2
              owner=root group=root mode=0644
    notify:
      - restart icecast

  - name: create default icecast2-beta config
    template: dest=/etc/default/icecast2-beta
              src=icecast/icecast_default.j2
              owner=root group=root mode=0644
    notify:
      - restart icecast

  - name: enable icecast2-beta on boot
    service: name=icecast2-beta enabled=yes state=started pattern=/usr/bin/icecast2-beta
    when: icecast is defined and icecast == 'yes'

  - name: disable icecast2-beta on boot
    service: name=icecast2-beta enabled=no state=stopped pattern=/usr/bin/icecast2-beta
    when: icecast is not defined or icecast == 'no'

  - name: create dump file directory for icecast
    file: dest=/srv/icecastdumps state=directory
          owner=icecast2-beta group=icecast-beta mode=0755
    when: icecast_push_master is defined and icecast_push_master == 'yes'
