---
  - include: ../../../register/bin_path.yml
  # Install packages needed for each relay
  - name: install streaming relay dependencies
    apt: name={{ item }} state=present
    with_items:
      - oggfwd-voc
  - include: ../../letsencrypt/tasks/main.yml domain={{ ansible_fqdn }}

  - include: nginx.yml
    tags: nginx
  - include: icecast.yml
    tags: icecast
  - include: iptables.yml
    tags: iptables
  - include: sysctl.yml
    tags: sysctl
