---
  # Install packages needed for each relay
  - name: install streaming relay dependencies
    apt: name={{ item }} state=present
    with_items:
      - oggfwd-voc
  - include: ../../letsencrypt/tasks/main.yml domain={{ ansible_fqdn }}

  - include: nginx.yml
  - include: icecast.yml
  - include: iptables.yml
  - include: sysctl.yml
