---
  - name: install nginx package
    apt: name=nginx-rtmp state=latest

  - name: configure nginx
    template: dest=/etc/nginx/nginx.conf
              src=nginx/nginx.conf.j2
              mode=0644 owner=root group=root
    notify:
      - restart nginx

  - name: start nginx
    service: name=nginx enabled=yes state=started
    when: nginx == 'yes'

  - name: stopp nginx
    service: name=nginx enabled=no state=stopped
    when: nginx != 'yes' or nginx is not defined
