---
  - name: install ntpd
    apt: name={{ item }} state=present
    with_items:
      - ntp
      - ntpdate

  - name: remove default ntp package
    apt: name=openntpd state=absent purge=yes

  - name: configure ntpd
    template: dest=/etc/ntp.conf
              src=ntpd/ntpd.conf.j2
              owner=root group=root mode=0644
    notify: restart ntpd

  - name: enable ntpd
    service: name=ntp enabled=yes state=started
