---
 - name: install a default set of packages
   apt: name={{ item }} state=present update_cache=yes
   with_items:
    - zsh
    - vim
    - htop
    - iftop
    - tcpdump
    - git
    - mtr-tiny
    - tmux
    - iperf
    - strace
    - iotop
    - screen
    - build-essential
    - gdb
    - bwm-ng
    - lldpd
    - ffmpeg
      #    - ffmpeg-voc
    - mosh
    - runit
    - molly-guard
    - ncdu
    - debian-goodies
    - apt-dater-host
    - dnsutils
    - subversion
    - dstat
    - pv
    - lm-sensors
    - moreutils
    - python
    - ruby
    - ruby-dev

 - name: install a vmware specific set of packages
   apt: name={{ item }} state=present update_cache=yes
   with_items:
     - open-vm-tools
   when: ansible_virtualization_type == 'VMware' and ansible_virtualization_role == role
