---
  # remove user when remove variable is defined
  - name: remove user "{{ user }}"
    user: state=absent remove=yes
         name={{ user }}
    when: remove is defined

  # realize user
  - shell: command -v zsh
    register: zsh_bin
    changed_when: false

  - name: create user "{{ user }}"
    user: state=present
          name="{{ user }}"
          groups="ssh,sudo,adm" append=yes
          shell={{ user_shell | default(zsh_bin.stdout) }}
    when: not remove is defined

  # addiotional groups
  - name: append libvirt and kvm group to user
    user: name={{ user }} append=yes groups=libvirt,kvm
    when: libvirtd_bin.stdout != '' and not remove is defined and ansible_virtualization_role == 'host'

  - name: append special groups on jessie systems
    user: name={{ user }} append=yes
          groups=systemd-journal,systemd-timesync,systemd-network,systemd-resolve
    when: ansible_distribution_release == 'jessie'

  # install shell stuff
  - name: install zshrc
    copy: dest="/home/{{ user }}/.zshrc" src="{{ item }}"
    with_first_found:
    - "user/{{ user }}/zshrc"
    - "user/default/zshrc"
    when: not remove is defined

  - name: install screenrc
    copy: dest="/home/{{ user }}/.screenrc" src="{{ item }}"
    with_first_found:
    - "user/{{ user }}/screenrc"
    - "user/default/screenrc"
    when: not remove is defined

  - name: add user's authorized_keys
    authorized_key: user="{{ user }}" manage_dir=true key="{{ lookup('file', item) }}" state=present
    with_fileglob:
     - "user/{{ user }}/authorized_keys"
    when: not remove is defined
