---
  # remove user when remove variable is defined
  - name: remove user "{{ user }}"
    user: state=absent remove=yes
         name={{ user }}
    when: remove is defined

  # realize user
  - name: create user "{{ user }}"
    user: state=present
          name="{{ user }}"
          groups="ssh,sudo,adm"
          shell={{ user_shell | default('/bin/zsh') }}
    when: not remove is defined and not ansible_virtualization_role == 'host'

  - name: create user "{{ user }}" on KVM host
    user: state=present
          name="{{ user }}"
          groups="ssh,sudo,adm,libvirt,kvm"
          shell={{ user_shell | default('/bin/zsh') }}
    when: not remove is defined and ansible_virtualization_role == 'host'

  - name: install zshrc
    copy: dest="/home/{{ user }}/.zshrc" src="{{ item }}"
    with_first_found:
    - "user/{{ user }}/zshrc"
    - "user/default/zshrc"
    when: not remove is defined

  - name: install screenrc
    copy: dest="/home/{{ user }}/.screenrc" src="{{ item }}"
    with_first_found:
    - "user/{{ user }}/screenrc"
    - "user/default/screenrc"
    when: not remove is defined

  - name: add user's authorized_keys
    authorized_key: user="{{ user }}" manage_dir=true key="{{ lookup('file', item) }}" state=present
    with_fileglob:
     - "user/{{ user }}/authorized_keys"
    when: not remove is defined
