---
 - name: create user "{{ user }}"
   user: name="{{ user }}" state=present shell=/bin/zsh groups="ssh,sudo"

 - name: setting voc password
   user: name=voc
         password={{ user_voc_password | default('$6$xQDo3Tyf$q8mxcBQTKmaGUA2cHuCS0QoeHSyYwESkyq/53OmEYLErMWF.CpS9Q3NzAoeB3zntZBpysfmEQ9r6sLjubLq5F1') }}
   when: user == 'voc'

 - name: install zshrc
   copy: dest="/home/{{ user }}/.zshrc" src="{{ item }}"
   with_first_found:
    - "user/{{ user }}/zshrc"
    - "user/default/zshrc"

 - name: install screenrc
   copy: dest="/home/{{ user }}/.screenrc" src="{{ item }}"
   with_first_found:
    - "user/{{ user }}/screenrc"
    - "user/default/screenrc"

 - name: add user's authorized_keys
   authorized_key: user="{{ user }}" manage_dir=true key="{{ lookup('file', item) }}" state=present
   with_fileglob:
     - "user/{{ user }}/authorized_keys"
