---
  # Copy shorewall config files to the right location and restart shorewall if
  # any change occur.
  - name: configure shorewall
    copy: dest=/etc/shorewall/{{ item }}
          src=shorewall/{{ item }} validate='shorewall check'
    with_items:
      - rules
      - interfaces
      - masq
      - policy
    notify:
      - restart shorewall
