---
  - hosts: audio-pis
    roles:
      - { role: common, tags: ['common'] }
      - { role: audio-pi, tags: ['audio-pi'] }
    vars:
      ssh_allow_voc_password_login: 'no'
      user_voc_password: "{{ lookup('keepass', 'ansible/logins/voc.password') }}"
