---
  - hosts: relays
    roles:
      - { role: common, tags: ['common'] }
      - { role: monitoring-client, tags: ['monitoring'] }
      - { role: relay, tags: ['relay'] }
    vars:
       user_voc_password: "{{ lookup('keepass', 'ansible/logins/voc.password') }}"
