---
  - hosts: servers
    roles:
      - { role: common, tags: ['common'] }
      - { role: monitoring-client, tags: ['monitoring'] }
      - { role: router, when: ansible_fqdn == 'router.lan.c3voc.de' }
      - { role: pbx, when: ansible_fqdn == 'phony.lan.c3voc.de' }
