---
  - hosts: tracker
    roles:
      - { role: common, tags: ['common'] }
      - { role: tracker, tags: ['tracker'] }
    vars:
      ssh_allow_voc_password_login: 'yes'
      user_voc_password: "{{ lookup('keepass', 'ansible/logins/voc.password') }}"

