---
  - name: install munin-node
    apt: name=munin-node state=present

  - name: configure the munin node
    copy: dest=/etc/munin/munin-node.conf
          src=munin-node.conf
          owner=root group=root mode=0644
    notify:
      - restart munin-node

  - name: create munin-fetch user
    user: name=munin-fetch groups=ssh
          home=/var/lib/munin-fetch
          shell=/bin/false

  - name: add SSH key to munin-fetch user
    authorized_key: user=munin-fetch manage_dir=true state=present
                    key="{{ lookup('file', 'authorized_keys') }}"

  - name: enable munin-node on boot
    service: name=munin-node enabled=yes state=started
