---
  - name: restart nginx
    service: name=nginx state=restarted

  - name: restart smbd
    service: name=smbd state=restarted

  - name: reload rc.local
    command: /etc/rc.local

  - name: reload rsync config
    service: name=rsync state=restarted
