---
  - name: deploy audio-ingest.sh
    template: src="audio-ingest.sh.j2"
              dest="/opt/audio-ingest.sh"
              mode=0755 owner=root group=root

  - name: create audio-ingest systemd-unit
    template: src="audio-ingest.service.j2"
              dest="/etc/systemd/system/audio-ingest.service"
              mode=0644 owner=root group=root

  - name: reload systemd daemon
    command: systemctl daemon-reload
    changed_when: false

  - name: enable & (re)start audio-ingest service
    service: name=audio-ingest.service
             enabled=yes
             state=restarted
